apiVersion: apps/v1
kind: Deployment
metadata:
  name: bostondataengineer-deploy
  labels:
    app: bostondataengineer-mvn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bostondataengineer-mvn-app
  template:
    metadata:
      labels:
        app: bostondataengineer-mvn-app
    spec:
      containers:
      - name: bostondataengineer-mvn-container
        image: bostondataengineer/bde-eta-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bostondataengineer-np-service
  labels:
    app: bostondataengineer-mvn-app
spec:
  selector:
    app: bostondataengineer-mvn-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
